spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  #    url: jdbc:postgresql://localhost:5432/sandbox
#    username: postgres
#    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    #show-sql: true
    #properties:
     # hibernate:
       # format_sql: true
